version: '3.0'

networks:
  frontend:
  backend:

volumes:
    influxdb-data:
    nodered-data: 
    grafana-data:
    jupyterlab-data:
    homeassistant-data:
    rhasspy-data:

services:
  nodered:
    restart: always
    build: ./nodered
    # image: nodered/node-red:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nodered/nodered-data:/data
    ports:
      - "1880:1880"
    #network_mode: "host"
    depends_on:
      - influxdb
      - mosquitto

  influxdb:
    restart: always
    build: ./influxdb
    environment:
      - INFLUXDB_DB=default
    volumes:
      - 'influxdb-data:/var/lib/influxdb'
    #network_mode: "host"
    ports:
      - "8086:8086"

#  tdengine:
#    restart: always
#    image: tdengine/tdengine
#    ports:
#      - 6020:6020
#      - 6030:6030
#      - 6035:6035
#      - 6030-6039:6030-6039/udp

  grafana:
    restart: always
    build: ./grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    volumes:
      - 'grafana-data:/var/lib/grafana'
    depends_on:
      - influxdb

  mosquitto:
    restart: always
    build: ./mosquitto
    #networks:
    #  - backend
#    network_mode: "host"
#    ports:
#      - "1883:1883"
#      - "1884:1884"

  emqx:
      image: emqx/emqx:latest
#      container_name: emqx
#      environment:
#      - "EMQX_NODE_NAME=emqx@node2.emqx.io"
#      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
#      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
#      healthcheck:
#        test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
#        interval: 5s
#        timeout: 25s
#        retries: 5
#      networks:
#        emqx-bridge:
#          aliases:
#          - node2.emqx.io
      ports:
        - 1883:1883
        - 8083:8083
        - 8084:8084
        - 8883:8883
        - 18083:18083
      # volumes:
      #   - $PWD/emqx2_data:/opt/emqx/data

#  jupyterlab:
#    restart: always
#    build: ./jupyterlab
#    ports:
#      - "8888:8888"
#    volumes:
#      - 'jupyterlab-data:/data'
#  homeassistant:
#    restart: always
#    build: ./homeassistant
#    ports:
#      - "8123:8123" 
#    volumes:
#      - 'homeassistant-data:/config'
#  rhasspy:
#    restart: always
#    build: ./rhasspy
#    ports:
#      - "12101:12101"
#    volumes:
#      - 'rhasspy-data:/profiles'
#    devices:
#      - "/dev/snd:/dev/snd"
#    command: --user-profiles /profiles --profile en
#  ap:
#    build: ./ap
#    restart: always
#    network_mode: host
#    privileged: true
#    labels:
#      io.balena.features.dbus: '1'
#      io.balena.features.firmware: '1'
#  bridge:
#    restart: always
#    build: ./bridge
#    depends_on:
#     - influxdb
#     - mosquitto
