version: '3'

networks: 
  network_smartedge:
      driver:  bridge

volumes:
    influxdb-data:
    nodered-data: 
    grafana-data:
    jupyterlab-data:
    homeassistant-data:
    rhasspy-data:

services:
  nodered:
    restart: always
    build: ./nodered
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - d:/SmartEdge/nodered-data:/data
      - ./nodered/nodered-config/settings.js:/data/settings.js
    ports:
      - "1880:1880"
    networks:
      - network_smartedge
    # network_mode: bridge
    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
    # network_mode: "host"
    #expose:
    #  - "1880:1880"
    depends_on:
      - influxdb
      - emqx

  influxdb:
    restart: always
    build: ./influxdb
    environment:
      - INFLUXDB_DB=default
    volumes:
      - d:/SmartEdge/influxdb-data:/var/lib/influxdb
    networks:
      - network_smartedge
    # network_mode: bridge
    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
    ports:
      - "8086:8086"

  tdengine:
    restart: always
    image: tdengine/tdengine:latest
    volumes:
      - d:/SmartEdge/taos/data:/var/lib/taos
      - d:/SmartEdge/taos/log:/var/log/taos
    networks:
      - network_smartedge
    # network_mode: bridge
    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
    ports:
      - 6030:6030 
      - 6041:6041 
      - 6043-6049:6043-6049 
      - 6043-6049:6043-6049/udp

  grafana:
    restart: always
    build: ./grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - network_smartedge
    # network_mode: bridge
    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
    ports:
      - "3000:3000"
    volumes:
      - d:/SmartEdge/grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

  mqtt:
    restart: always
    build: ./mosquitto
    #networks:
    #  - backend
#    network_mode: "host"
#    ports:
#      - "1883:1883"
#      - "1884:1884"

  emqx:
    restart: always
    image: emqx/emqx:latest
#      container_name: emqx
#      environment:
#      - "EMQX_NODE_NAME=emqx@node2.emqx.io"
#      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
#      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
#      healthcheck:
#        test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
#        interval: 5s
#        timeout: 25s
#        retries: 5
#      networks:
#        emqx-bridge:
#          aliases:
#          - node2.emqx.io
    networks:
      - network_smartedge
    # network_mode: bridge
    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - d:/SmartEdge/emqx_data:/opt/emqx/data